### ISSUE TITLE
Commas are included in AtWord nodes

### ISSUE THREAD

**Issue by jwilsson** [lesshint/postcss-values-parser#2]
Take the following input:
```css
color: rgb(@a, @b, @c);
```

which will result in this AST:
```js
[...]
AtWord {
  raws: { before: '', after: '' },
  value: 'a,', 
  source: { start: { line: 1, column: 5 }, end: { line: 1, column: 7 } },
  sourceIndex: 4,
  nodes: [],
  type: 'atword',
}
[...]
```

I would expect a `Comma` node after each `AtWord` node.

I found that using the same regex currently used for `Word` nodes for `AtWord` nodes too seems to solve it, it needs some more tests though.

But I don't know how we should handle it since it's not something that will happen while writing regular CSS, is it out of the scope for this and something we should handle in `lesshint` or include it here? @shellscape

**Comment by jwilsson** [comment]
On second thought, it's probably better to just include commas in the `atEnd` regex.

**Comment by shellscape** [comment]
@jwilsson what is the output when it's just something like `rgb(255, 255, 255)`? That's the pattern we should follow.

**Comment by jwilsson** [comment]
The output's the expected one, `Number` and then `Comma`.

I'll send a PR momentarily.
