### ISSUE TITLE
Incorrect parsing of custom properties

### ISSUE THREAD

**Issue by jacobp100** [lesshint/postcss-values-parser#7]
`--color` shows up as an operator and then a word, when per spec, this should be a single word.

**Comment by shellscape** [comment]
thanks for the report. would gladly review a PR to resolve this.

**Comment by shellscape** [comment]
@jacobp100 got a link to the spec describing this?

**Comment by jacobp100** [comment]
Sorry, I'll make sure I link the relevant spec next time! It's part of the [custom variables spec](https://www.w3.org/TR/css-variables-1/#defining-variables)

**Comment by shellscape** [comment]
fix for custom vars is here: https://github.com/lesshint/postcss-values-parser/blob/es6-refactor/lib/tokenize.js#L196

need to do a little more work on this and then I'll push it out
