### ISSUE TITLE
Negative and positive numbers parsed as two tokens

### ISSUE THREAD

**Issue by jacobp100** [lesshint/postcss-values-parser#8]
Both `-2` and `+2` are parsed as an operator and a number. The spec says these should both be numbers.

There is also a test for `5+5`, which should actually fail.

**Comment by shellscape** [comment]
thanks for the report. would gladly review a PR to resolve this.

**Comment by jacobp100** [comment]
I tried! I couldn’t get my head around the parser. 😟

**Comment by shellscape** [comment]
this week is a little nutty for me, so I may not get to a fix until the weekend.

**Comment by shellscape** [comment]
tracked down the bit of the spec that pertains to this. https://drafts.csswg.org/css-values-3/#calc-syntax. in the future, please do that legwork if you're quoting the spec. I'll see about applying these rules.

**Comment by jacobp100** [comment]
Sorry, I should have linked it! For reference, it's also in the [syntax module](https://www.w3.org/TR/css-syntax-3/#typedef-number-token) under `<number-token>`.

**Comment by shellscape** [comment]
no worries. I'm refactoring the whole thing at the moment to do away with babel, so it'll be a bit until that's done, and then I can tackle the two +/- issues. fwiw, the tokenizer is where the issue is and that's just one big while loop.

**Comment by jacobp100** [comment]
I got that far, I couldn’t figure out how to get `wordEnd` and `wordEndNum` to co-operate. Do you have a branch for the refactor?

**Comment by shellscape** [comment]
Yeah I literally just pushed it :) https://github.com/lesshint/postcss-values-parser/blob/es6-refactor/test/number.js are the new tests I've added.

here's where the bit that looks around an operator now lives https://github.com/lesshint/postcss-values-parser/blob/es6-refactor/lib/tokenize.js#L197 that should fix the issue. I've started throwing `TokenizeError` for things that shouldn't pass validation. and I've been using https://jigsaw.w3.org/css-validator/validator to double check the validation, along with the spec.
